// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Test is the predicate function for test builders.
type Test func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
