version: "3"

tasks:
  default:
    cmds:
      - echo Hello, World!

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  init:
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans
      - docker compose up -d

  build:
    cmds:
      - docker compose build

  generate:
    dir: ./app
    cmds:
      - docker exec sleeve-be gqlgen generate

  lint-fmt:
    dir: ./app
    cmds:
      - docker exec sleeve-be golangci-lint run
