// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sleeve/ent/schema"
	"sleeve/ent/test"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	testFields := schema.Test{}.Fields()
	_ = testFields
	// testDescTitle is the schema descriptor for title field.
	testDescTitle := testFields[0].Descriptor()
	// test.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	test.TitleValidator = testDescTitle.Validators[0].(func(string) error)
	// testDescDone is the schema descriptor for done field.
	testDescDone := testFields[1].Descriptor()
	// test.DefaultDone holds the default value on creation for the done field.
	test.DefaultDone = testDescDone.Default.(bool)
}
