// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sleeve/ent/schema"
	"sleeve/ent/test"
	"sleeve/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	testFields := schema.Test{}.Fields()
	_ = testFields
	// testDescTitle is the schema descriptor for title field.
	testDescTitle := testFields[0].Descriptor()
	// test.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	test.TitleValidator = testDescTitle.Validators[0].(func(string) error)
	// testDescDone is the schema descriptor for done field.
	testDescDone := testFields[1].Descriptor()
	// test.DefaultDone holds the default value on creation for the done field.
	test.DefaultDone = testDescDone.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPublicID is the schema descriptor for public_id field.
	userDescPublicID := userFields[0].Descriptor()
	// user.DefaultPublicID holds the default value on creation for the public_id field.
	user.DefaultPublicID = userDescPublicID.Default.(func() uuid.UUID)
	// userDescFirebaseUID is the schema descriptor for firebase_uid field.
	userDescFirebaseUID := userFields[1].Descriptor()
	// user.FirebaseUIDValidator is a validator for the "firebase_uid" field. It is called by the builders before save.
	user.FirebaseUIDValidator = userDescFirebaseUID.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
