// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sleeve/ent/predicate"
	"sleeve/ent/test"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestUpdate is the builder for updating Test entities.
type TestUpdate struct {
	config
	hooks    []Hook
	mutation *TestMutation
}

// Where appends a list predicates to the TestUpdate builder.
func (_u *TestUpdate) Where(ps ...predicate.Test) *TestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TestUpdate) SetTitle(v string) *TestUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TestUpdate) SetNillableTitle(v *string) *TestUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDone sets the "done" field.
func (_u *TestUpdate) SetDone(v bool) *TestUpdate {
	_u.mutation.SetDone(v)
	return _u
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (_u *TestUpdate) SetNillableDone(v *bool) *TestUpdate {
	if v != nil {
		_u.SetDone(*v)
	}
	return _u
}

// Mutation returns the TestMutation object of the builder.
func (_u *TestUpdate) Mutation() *TestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := test.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Test.title": %w`, err)}
		}
	}
	return nil
}

func (_u *TestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(test.Table, test.Columns, sqlgraph.NewFieldSpec(test.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(test.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Done(); ok {
		_spec.SetField(test.FieldDone, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TestUpdateOne is the builder for updating a single Test entity.
type TestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestMutation
}

// SetTitle sets the "title" field.
func (_u *TestUpdateOne) SetTitle(v string) *TestUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TestUpdateOne) SetNillableTitle(v *string) *TestUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDone sets the "done" field.
func (_u *TestUpdateOne) SetDone(v bool) *TestUpdateOne {
	_u.mutation.SetDone(v)
	return _u
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (_u *TestUpdateOne) SetNillableDone(v *bool) *TestUpdateOne {
	if v != nil {
		_u.SetDone(*v)
	}
	return _u
}

// Mutation returns the TestMutation object of the builder.
func (_u *TestUpdateOne) Mutation() *TestMutation {
	return _u.mutation
}

// Where appends a list predicates to the TestUpdate builder.
func (_u *TestUpdateOne) Where(ps ...predicate.Test) *TestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TestUpdateOne) Select(field string, fields ...string) *TestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Test entity.
func (_u *TestUpdateOne) Save(ctx context.Context) (*Test, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestUpdateOne) SaveX(ctx context.Context) *Test {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := test.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Test.title": %w`, err)}
		}
	}
	return nil
}

func (_u *TestUpdateOne) sqlSave(ctx context.Context) (_node *Test, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(test.Table, test.Columns, sqlgraph.NewFieldSpec(test.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Test.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, test.FieldID)
		for _, f := range fields {
			if !test.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != test.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(test.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Done(); ok {
		_spec.SetField(test.FieldDone, field.TypeBool, value)
	}
	_node = &Test{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{test.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
