// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthTokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type RegisterUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterUserPayload struct {
	User   *RegisteredUser `json:"user"`
	Tokens *AuthTokens     `json:"tokens"`
}

type RegisteredUser struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
