-- Create "tests" table
CREATE TABLE "public"."tests" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "done" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
