run:
  go: "1.25"
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - nolintlint
    - unconvert

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - '.*_gen\.go'
    - 'graph/generated.go'
  exclude-rules:
    # Exclude specific linters in test files
    - path: '_test\.go'
      linters:
        - errcheck # Allow unchecked errors in tests
