package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"sleeve/graph/model"
	"sleeve/usecase/user"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.RegisterUserInput) (*model.RegisterUserPayload, error) {
	var result *model.RegisterUserPayload
	var usecase_result *user.RegisterUserResult
	var err error

	usecase_result, err = r.RegisterUserUseCase.Execute(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	result = &model.RegisterUserPayload{
		User: &model.RegisteredUser{
			ID:    usecase_result.User.PublicID().String(),
			Email: usecase_result.User.Email().Value(),
		},
		Tokens: &model.AuthTokens{
			AccessToken:  usecase_result.AccessToken,
			RefreshToken: usecase_result.RefreshToken,
		},
	}
	return result, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
